# Generated by Django 2.0.13 on 2019-04-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(default='', max_length=140)),
                ('cantidad', models.IntegerField(default=0)),
                ('fechavencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Productosconsumido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadconsumida', models.IntegerField(default=0)),
                ('nombre', models.ForeignKey(on_delete='on_delete', to='monoku.Participante')),
                ('nombreproducto', models.ForeignKey(on_delete='on_delete', to='monoku.Producto')),
            ],
        ),
    ]
