# Generated by Django 2.0.13 on 2019-05-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monoku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumosMayores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_participante', models.CharField(max_length=140)),
                ('catidad_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='participante',
            name='nombre',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreproducto',
            field=models.CharField(max_length=140),
        ),
    ]
