# Generated by Django 2.0.13 on 2019-05-15 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monoku', '0002_auto_20190514_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsumosMayores',
        ),
    ]
